#!/bin/bash
#
function absolute_path { 
	if [ ${1:0:1} == / ]
	then
	echo "$1"
	else
	[[ -e $1 ]] && echo "$PWD/$1" || echo "$1::_No_such_file_or_directory" 
	fi
}
#  about this dict(ionary):
#  Northward/Eastward turbulent surface stress
#  Northward surface stress due to turbulent processes. Accumulated field.
#  FST name is AW for module of it.  Here introduce components of AW: AWNS and AWEW.  
#  no units change.  Instantaneous would be FQ in FST  [Pa]
#
# get grib files fst output dir and log directory from cl argument
if [ _$1 = '_' -o _$2 = '_' -o _$3 = '_' -o _$4 = '_' -o _$5 = '_' ]
then
echo -e 'Calling sequence is '$0' grib-FOLDER grib-files-mask grib-files-extension fst-dir logs-dir\n'
exit
fi
#
# precautions
#
[ -f $1 ] && echo -e $1 $2 \\n first argument must be a directory not a _file_ && exit  1 
#
DIR1=`dirname ${1}/_`
RA_VG=`absolute_path $DIR1`
GRB_MASK=$2
GRB_EXT=$3
fstdir=`absolute_path $4`
g2f_logs=$5
echo arguments: $1 $2 $3 $4 $5 
echo $DIR1
echo RA_VG:$RA_VG
echo fstdir:$fstdir
echo g2f_logs:$g2f_logs
#
# precautions
#
[ ! -d $4 ] && mkdir -p $4
[ ! -d $5 ] && mkdir -p $5
#exit
#
grib2fst=ahGRB2FST
#
cat > ahdict_ <<FIN
shortName grbunits is2D3D nomvar fstunits mult add
'10u'        'm/s'      '2D'     'UU'      'kt'     1.94384   0
'10v'        'm/s'      '2D'     'VV'      'kt'     1.94384   0
'z'  'm2/s2'  '3D' 'GZ'  'dam' 0.010197162  0.0
'z'  'm2/s2'  '2D' 'ME'  'dam' 0.010197162  0.0
't'  'degK'  '3D' 'TT' 'degC'  1.0   -273.15
'r'  '1'  '3D'  'HR'  '%'      100.  0.
'nsss' 'N/m2*s'  '2D'  'AWNS' 'Pa*s'  1  0
'ewss' 'N/m2*s'  '2D'  'AWEW' 'Pa*s'  1  0
FIN
sed -e 's/\s\+/,/g' ahdict_ >ahdict
#
set -x
#
ls -al ${RA_VG}/${GRB_MASK}*${GRB_EXT}
mkdir -f $fstdir
#
for GRIBfile in ${RA_VG}/${GRB_MASK}*${GRB_EXT}
do
	gribsuffix=."${GRIBfile##*.}"
	gribdir=`dirname $GRIBfile`
	nombase=`basename --suffix=${gribsuffix} ${GRIBfile}`
	# FSTfile=${gribdir}/${nombase}.fst
	FSTfile=${fstdir}/${nombase}.fst
	cat > ahcontrols <<FIN
	&controls
	 grib='$GRIBfile'
	 fst='$FSTfile'
	! rootfst='$nombase'
	! months=1,2   ! specify first and last month to convert to FST files
	 catch2d='10u','10v','nsss','ewss','z'   ! z for topography 2d
	 catch3d='z','t','r'
	/
FIN
	cat ahdict >> ahcontrols
	echo -e "\ngribfile: $GRIBfile\nfstfile: $FSTfile\n"
	rm -f $FSTfile
	$grib2fst < ahcontrols 2>&1 | tee ${g2f_logs}/${nombase}.log
done
#
#  clean up
rm ahcontrols ahdict* *~
#
